package com.connorcode;

public class wordList {
    public static String[] goodWords = {
            "good",
            "acceptable",
            "excellent",
            "exceptional",
            "favorable",
            "great",
            "marvelous",
            "positive",
            "satisfactory",
            "satisfying",
            "superb",
            "valuable",
            "wonderful",
            "ace",
            "boss",
            "bully",
            "capital",
            "choice",
            "crack",
            "nice",
            "pleasing",
            "prime",
            "rad",
            "sound",
            "spanking",
            "sterling",
            "super",
            "superior",
            "welcome",
            "worthy",
            "admirable",
            "agreeable",
            "commendable",
            "congenial",
            "deluxe",
            "first-class",
            "first-rate",
            "gnarly",
            "gratifying",
            "honorable",
            "neat",
            "precious",
            "reputable",
            "select",
            "shipshape",
            "splendid",
            "tip-top"};

    public static String[] badWords = {
            "exceptional",
            "improved",
            "superior",
            "choice",
            "exceeding",
            "fitter",
            "preferred",
            "sophisticated",
            "surpassing",
            "bigger",
            "finer",
            "greater",
            "higher quality",
            "larger",
            "more appropriate",
            "more desirable",
            "more fitting",
            "more select",
            "more suitable",
            "more useful",
            "more valuable",
            "preferable",
            "prominent",
            "souped up",
            "worthier"};
}
