name: fast-doll::build
on:
  push:
    paths:
      - "fast-doll/**"
      - ".github/workflows/fast-doll.yml"

env:
  PROJECT: fast-doll

jobs:
  build:
    strategy:
      matrix:
        java: [21]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Chmod gradlew
        if: ${{ runner.os != 'Windows' }}
        working-directory: ./${{ env.PROJECT }}
        run: chmod +x ./gradlew
      - name: Build
        working-directory: ./${{ env.PROJECT }}
        run: ./gradlew build
      - name: Upload Artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            ${{ env.PROJECT }}/build/libs/*.jar
            !${{ env.PROJECT }}/build/libs/*-sources.jar
